---
version: '3.4'
services:
  geth:
    image: com.dwightaspencer.blockchian.geth:${IMAGE_VERSION}
    hostname: "${VIRTUAL_HOST}"
    #logging:
    #  driver: "syslog"
    #  options:
    #    syslog-address:  "tcp://{{.Status.Addr}}:6514"
    deploy:
      restart_policy: 
        condition: on-failure
      replicas: 1
      labels:
        - traefik.enabled=true
        - traefik.docker.network=public
        - traefik.port=8545
        - traefik.frontend.priority=5
        - traefik.frontend.entryPoints="http, https"
        - traefik.frontend.rule="Host:${VIRTUAL_HOST}"
        - orbiter.enabled=false
        - com.centurylinklabs.watchtower.enabled=false
        traefik.port: "8545"
        traefik.frontend.priority: "10"
        traefik.frontend.entryPoints: "http, https"
        traefik.frontend.rule: "Host:dtr.local"
        traefik.docker.network: "public"
        traefik.enabled: "true"
        traefik.frontend.auth.basic: "dtr:$$apr1$$9Cv/OMGj$$ZomWQzuQbL.3TRCS81A1g/" # dtr:password
        orbiter: "false"
        com.centurylinklabs.watchtower.enable: "true"
    ports:
      - "30303:30303"
      - "8545/tcp"
    networks:
      public:
        aliases:
          - "geth"
          - "${VIRTUAL_HOST}"
    volumes:
      - gethdata:/root/files

volumes:
  gethdata:

networks:
  public:
    external:
      name: public

...
# vim: set sts=2 sw=2 ts=2 et ai :
